import {
    attribute,
    autoGeneratedHashKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';
import { embed } from '@aws/dynamodb-data-mapper';
import { AuthToken } from './authToken'

@table('users')
export class User {
    @autoGeneratedHashKey()
    userId: string;
    @attribute({ defaultProvider: () => new Date() })
    created: Date;
    @attribute({ type: 'String', indexKeyConfigurations: { "username": "HASH" } })
    username: string;
    @attribute()
    password: string;
    @attribute()
    active: boolean;
    @attribute({ memberType: embed(AuthToken) })
    tokens?: Array<AuthToken>;
}